$(document).ready(
  function(){
    $(".pay").click(
      function(){
        $(".menu").toggleClass("active");
      }
    );
    $(".who").click(
      function(){
        $(".who_menu").toggleClass("active");
      }
    );
  }
)
